# User config
author: "Zhenyu Zheng"
tagline: "Arm CI Landscape"
description: "Arm CI Landscape"
keywords: "Arm, CI, Landscape"
email: "zheng.zhenyu@outlook.com"
github: "https://kunpengcompute.github.io/"

# Site config
baseurl: "/arm-landscape"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
