# User config
author: "MulanOS"
title: "木兰Aarch64开源生态全景平台"
tagline: "Landscape"
description: "Landscape"
keywords: "Landscape"

# Site config
baseurl: "/landscape-for-arm"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
