# User config
author: "Zhenyu Zheng"
tagline: "Arm CI Landscape"
description: "Arm CI Landscape | The following open source projects now have Arm CI"
keywords: "Arm, CI, Landscape"
email: "landscape@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/arm-landscape"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
