# User config
author: "Zhenyu Zheng"
title: "木兰ARM开源生态全景平台"
tagline: "Landscape"
description: "Landscape"
keywords: "Landscape"
email: "zheng.zhenyu@outlook.com"

# Site config
baseurl: "/landscape-for-arm"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
